# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anomaly.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'anomaly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranomaly.proto\"h\n\x0e\x41nomalyRequest\x12\x12\n\namount_due\x18\x01 \x01(\x01\x12\x13\n\x0b\x61mount_paid\x18\x02 \x01(\x01\x12\x12\n\ndelay_days\x18\x03 \x01(\x05\x12\x19\n\x11paid_to_due_ratio\x18\x04 \x01(\x01\"<\n\x0f\x41nomalyResponse\x12\x15\n\ranomaly_score\x18\x01 \x01(\x01\x12\x12\n\nis_anomaly\x18\x02 \x01(\x08\"b\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x12\n\namount_due\x18\x01 \x01(\x01\x12\x13\n\x0b\x61mount_paid\x18\x02 \x01(\x01\x12\x12\n\ndelay_days\x18\x03 \x01(\x05\x12\x12\n\nuser_label\x18\x04 \x01(\x05\"#\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\x0e\x41nomalyService\x12+\n\x06\x44\x65tect\x12\x0f.AnomalyRequest\x1a\x10.AnomalyResponse\x12\x35\n\x0eSubmitFeedback\x12\x10.FeedbackRequest\x1a\x11.FeedbackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anomaly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANOMALYREQUEST']._serialized_start=17
  _globals['_ANOMALYREQUEST']._serialized_end=121
  _globals['_ANOMALYRESPONSE']._serialized_start=123
  _globals['_ANOMALYRESPONSE']._serialized_end=183
  _globals['_FEEDBACKREQUEST']._serialized_start=185
  _globals['_FEEDBACKREQUEST']._serialized_end=283
  _globals['_FEEDBACKRESPONSE']._serialized_start=285
  _globals['_FEEDBACKRESPONSE']._serialized_end=320
  _globals['_ANOMALYSERVICE']._serialized_start=322
  _globals['_ANOMALYSERVICE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
